### ISSUE TITLE
haproxy17u on EL6

### ISSUE THREAD

**Issue by kaushalshriyan** [iuscommunity-pkg/haproxy17u#1]
What package do you want?

haproxy 1.7
Why?

HAProxy 1.7 brings more reliability to HAProxy
OS versions

I would like this package for RHEL 6 / CentOS 6.
Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
I have created a [new release](https://github.com/iuscommunity-pkg/haproxy17u/releases/tag/1.7.2-2) that adds EL6 support to the spec file.  The new packages will move to our testing repositories during tonight's automation.

**Comment by kaushalshriyan** [comment]
@carlwgeorge Thanks a lot and really appreciated !!!

**Comment by b-harper** [comment]
Hey @kaushalshriyan,

I just wanted to check in and see if you had a chance to test the EL6 packages.  HAProxy released a [new version][0] and updated packages will be hitting the testing repositories during tonight's automation run.

[0]: https://www.mail-archive.com/haproxy@formilux.org/msg25066.html

**Comment by kaushalshriyan** [comment]
@b-harper Thanks for the followup. I have tested it and it is working as expected. Sorry for the delay.

**Comment by b-harper** [comment]
@kaushalshriyan,

Thank for the feedback.  The haproxy17u-1.7.2-2 packages will get moved to the stable repositories during tonight's automation run.
