### ISSUE TITLE
openssl dependeny fails

### ISSUE THREAD

**Issue by andrm** [iuscommunity-pkg/haproxy17u#2]
I can't update haproxy17u. Any hints what I got wrong?

```
# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.netcologne.de
 * epel: mirror.wiuwiu.de
 * extras: mirror.netcologne.de
 * ius: mirror.amsiohosting.net
 * updates: mirror.netcologne.de
Resolving Dependencies
--> Running transaction check
---> Package haproxy17u.x86_64 0:1.7.8-1.ius.el7 will be updated
---> Package haproxy17u.x86_64 0:1.7.9-1.ius.el7 will be an update
--> Processing Dependency: libcrypto.so.10(OPENSSL_1.0.2)(64bit) for package: haproxy17u-1.7.9-1.ius.el7.x86_64
--> Finished Dependency Resolution
Error: Package: haproxy17u-1.7.9-1.ius.el7.x86_64 (ius)
           Requires: libcrypto.so.10(OPENSSL_1.0.2)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by carlwgeorge** [comment]
My guess is that you are trying to use our RHEL repository on a CentOS system.  We have [separate repositories](https://ius.io/GettingStarted/#ius-release) for RHEL and CentOS.  Normally you wouldn't have problems, but we are in the window between the RHEL release and the corresponding CentOS release.  In this case what you are seeing is that the haproxy17u package you are trying to use was built against RHEL 7.4's OpenSSL 1.0.2, but CentOS 7.3 is still on OpenSSL 1.0.1.

`Requires: libcrypto.so.10(OPENSSL_1.0.2)(64bit)`

**Comment by andrm** [comment]
Bingo, I missed the point that you have separate centos repos. Fixed. Thanks a lot!
