### ISSUE TITLE
Plans to support 1.8?

### ISSUE THREAD

**Issue by kustodian** [iuscommunity-pkg/haproxy17u#3]
Because 1.8 stable is out, do you have any plans to support it? We are willing to test it out and start using it in production.

**Comment by carlwgeorge** [comment]
This repo is for haproxy 1.7 only.  1.8 would be a different package in our [naming scheme](https://ius.io/Philosophy/#naming-convention).  New package requests belong on our [wishlist tracker](https://github.com/iuscommunity/wishlist).  haproxy18u has [already been requested](https://github.com/iuscommunity/wishlist/issues/161).
